### ISSUE TITLE
Access folders outside snap

### ISSUE THREAD

**Issue by rhazegh** [arubislander/subsonic-snap#2]
Thanks for making this snap.

I am trying to access my music folder that is mounted from another file system on `/mnt/music/` from inside snap but I get `Folder not found`.

<img width="843" alt="screenshot 2018-09-19 10 11 44" src="https://user-images.githubusercontent.com/2200559/45758802-7be7c000-bbf4-11e8-9ade-cbd0500fc6dd.png">

I created a soft link to `/mnt/music/` inside `/root/snap/subsonic-arubislander/common/var/music/` but that didn't work either.

Any idea how I can access `/mnt/music/`?

**Comment by rhazegh** [comment]
Used `mount --bind /mnt/music /root/snap/subsonic-arubislander/common/var/music/audio` and then used `/root/snap/subsonic-arubislander/common/var/music/audio` folder to scan for media. It does not complain and saves. BUT, when I scan for media, it does not find anything:

```
[2018-09-19 11:00:10,331] INFO MediaScannerService - Starting to scan media library.
[2018-09-19 11:00:10,360] INFO MediaScannerService - Scanned media library with 2 entries.
[2018-09-19 11:00:10,361] INFO MediaScannerService - Marking non-present files.
[2018-09-19 11:00:10,362] INFO MediaScannerService - Marking non-present artists.
[2018-09-19 11:00:10,363] INFO MediaScannerService - Marking non-present albums.
[2018-09-19 11:00:10,366] INFO MediaScannerService - Completed media library scan.
[2018-09-19 11:00:10,665] INFO PlaylistService - Starting playlist import.
[2018-09-19 11:00:10,667] INFO PlaylistService - Completed playlist import.
```

PS:
Snaps are a good idea but are executed in a way that makes them worthless. That's why people use Windows and MacOS. What a waste of time. 😞

**Comment by rhazegh** [comment]
Never mind. I just installed Subsonic directly as an application. Cheers.

**Comment by arubislander** [comment]
Hi, thank you for reaching out! Also thank you for giving the snap a go.
I have experienced the same issue you have. What worked for me was not to mount bind the folder under the /root/snap/.../ folder but under /media/subsonic/. 
The snap can be given permission to access to removable media with:
`sudo snap connect subsonic-arubislander:removable-media`

I would like to encourage you to give this a try. Of course installing subsonic as an application directly is a perfectly valid solution for you. But the advantage of going the snap route for me, and the reason why I created the snap, is so that I needn't worry about manually updating the software on my 'production' server. If and when upstream releases a new version of Subsonic, as soon as I package it as a snap (which shouldn't take long at all) within 24 hours of releasing it, my production service would be updated automatically

I have re-opened the issue pending your reaction. And if you encounter any issues, I am willing to help you resolve them.

**Comment by rhazegh** [comment]
Your snap package worked fine 👍I already wasted too much time on snap. I will try it in a year or 2 when it's mature enough. Thank you :)

**Comment by arubislander** [comment]
Thank you for getting back to me. I am sorry snaps don't fit into your workflow. Maybe see you again in a year or 2, and Cheers!

**Comment by mrbracchi** [comment]
Hi there!
Why is it that you have to use the mount --bind command instead of a symlink? I was previously trying to simlink into /media and it would read the tracks but not play any of them. Also, I'm not having any luck accessing the server from other computers on my LAN or using any of my apps. Does the " $ snap set subsonic-arubislander host=192.168.1.10 port=8080 context-path="/subsonic" max-memory=450" command need to be for the host ip that the snap is running on? I want to leave the port as 4040 if possible . . . thanks for your work on this and any help provided!!

**Comment by arubislander** [comment]
Thank you for your question.

re. symlink vs mount-bind: I don't remember exactly if I tried symlinks or not. I think I did, but they did not work correctly, as you yourself experienced. I think it has to do with that symlinks honor the original permissions of whatever it is they link to.

re the IP address: yes, you set that to the network visible ip address of the server the snap is running on.

**Comment by mrbracchi** [comment]
** Solved, I didn't open the port on my firewall. DUH! **Thanks for your response! I am not having any luck accessing my server on a different machine on the same lan/wan. the host ip of the server is 192.168.0.46 and I run the command sudo snap set subsonic-arubislander host=192.168.0.46 port=4040 context-path="/subsonic" max-memory=450
but everything just times out after awhile.

**Comment by arubislander** [comment]
Oh yeah, that bit me too, once... What distro are you running on?

**Comment by mrbracchi** [comment]
KDE Neon. I'm going to switch distros this summer though. Thinking of Xbuntu. How hard was crafting the snap? There are some open source versions of subsonic that I was thinking of trying to snap just to learn something new. This is what I was thinking I might try to snap if it's not too hard and licenses allow. https://airsonic.github.io/

**Comment by arubislander** [comment]
It wasn't too difficult to snap up subsonic. I used the self contained .war installation and just tweaked the paths in a wrapper script. Figuring out the dependencies was the hardest part.

To snap airsonic I would imagine using my snapcraft.yaml as a base and just swapping out the url for the war file and going over all the subsonic references and adjusting accordingly should give you a head start.

I had been meaning to try my hand at it myself. So if you give it a go, let me know, I will happily contribute PR's

**Comment by utopianfish** [comment]
Hi i've installed this onto a raspberry pi virtual machine..my music is on an additional drive which has a mount point / media/external_drive.... subsonic sees the folder but will not bring in any of the files.... i have tried the command sudo snap connect subsonic-arubislander:removable-media but its still the same .. what am i missing.... ?  thanks.. i have subsonic running on a windows VM at the mo but wanted to try linux.. thanks...

**Comment by arubislander** [comment]
Hi,

Thank you for your interest in using the Subsonic snap.

Could you tell me what format your media files are? Or maybe the folder
structure is what is tripping up the application? I have had media be
ignored in the past when the folder structure was not what Subsonic
expected. What works for me is Artist/Album/media.file

Thanks!

**Comment by utopianfish** [comment]
Hi

Folder structure is iTunes/ artist /album/songs. Mixture of m4a and.flac..
tried copying one folder to the root of the folder and it still doesn’t
find it.

**Comment by arubislander** [comment]
Could you try adding an .mp3 or .ogg file somewhere there? Also, what does
your configuration look like in Subsonic?

**Comment by utopianfish** [comment]
Ok the odd thing is now that I tried it on a Debian vm and it works… the
mount point is not under / media but is under /mnt/mymusic.. apart from
that it’s the same so not sure why the raspberry pi setup doesn’t work…

**Comment by arubislander** [comment]
You have a raspberry pi VM image? How does that work? Is it arm64 or amd64?

Also, what is the filesystem on that additional drive?

**Comment by utopianfish** [comment]
Hi i'll stick with the working debian version i have.. was just curious why the pi install just wouldnt  pick up the folders.. thanks anyway and thanks for a nice piece of software
